import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Button, Link as MuiLink, Typography } from "@material-ui/core";
import Routes from "../constants/routes";
import { useSnackbar } from "notistack";
import withAuth from "../hocs/withAuth";
import { useAuth } from "../lib/auth";
function Home() {
  const { logout } = useAuth();
  const { enqueueSnackbar } = useSnackbar();

  const handleLogout = async () => {
    logout();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography align="center">Bienvenido a Search Health</Typography>
      <Typography variant="subtitle1" align="center">
        Menú en construcción
      </Typography>

      <Button
        variant="contained"
        color="secondary"
        onClick={() => handleLogout()}
      >
        Cerrar sesión
      </Button>
    </div>
  );
}

export default withAuth(Home);
