import Head from "next/head";
import { Button, Drawer, Link as MuiLink, Typography } from "@material-ui/core";
import withoutAuth from "../hocs/withAuth";
import { useAuth } from "../lib/auth";
import { useRouter } from "next/router";

function Home() {
  const { user } = useAuth();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Ver la manera de que me redrijia al Admin en caso de ser administrador*/}
      <Typography>Bienvenido a Search Health</Typography>
    </>
  );
}

export default Home;
